### ISSUE TITLE
数据库文件不见了

### ISSUE THREAD

**Issue by yzhym** [PaleNeutron/Pcrd-Wiki#4]
看了一下自己的data文件夹，资源倒是解析出来了，但是数据库文件没有找到，就是名字是sha1("master.mdb")那个，files/manifest下面只有一堆资源目录文档(txt?)
看了files下面的资源路径数据库manefest.db，其中有两个记录a/masterdata_master_0003.cdb和a/masterdata_master.cdb，分别对应的应该是a下面的6954b4dcc783fe45453fb742848f47a128485903和cc5f9ab5ca66772741a420e83ef3d056bdf8dbae，和a下面其他文件不同不是unity3d文件，不知道是什么格式以及与数据库是否有什么关系

**Comment by PaleNeutron** [comment]
我弃坑一段时间了,手里没有最新的客户端, 貌似是曾经有人反馈过数据库文件找不到了, 你确定现在`files/manifest`里没有一个特别大的(5M+)的文件了吗?

**Comment by yzhym** [comment]
files/manifest下每个文件我都看过了，都是单纯资源路径文本，最大300k，整个files我按sqlite文件头找了一遍也就只有files/manifest.db，5M以上的文件目前只有files/b和files/m下面的几个文件，不过应该都是bgm和movie吧，文件头是AFS2和CRID

**Comment by PaleNeutron** [comment]
那应该是换地方了, 我试试看重新逆向一下, 看能不能找到新的数据库在哪里

**Comment by superk589** [comment]
Cygames 已经对数据库加密了，原来的方式已经不行了

> https://estertion.win/2018/08/プリコネr-1-6-与-cdb、通信加密-与-coneshell-dll/

如果只希望要最新的数据库文件，而不关心具体的提取逻辑，可以直接用这个
https://redive.estertion.win/api.htm

希望研究具体的提取逻辑可以结合这篇文章
https://estertion.win/2018/09/重拾cdb/
以及代码库
https://github.com/esterTion/unity-texture-toolkit

以上所有内容来自 esterTion 大佬，希望这些东西对解决这个问题有所帮助

**Comment by yzhym** [comment]
我自己刚才瞎找找到了一个数据库，数据库跟图片素材一样封装成unity3d文件了，导出来叫master.txt，实质上是sqlite数据库，不过看了一下unit数据发现9月新角色的数据都是0，10月的直接没有，看来是旧库了，顺便这个库大小3M，对应unity3d文件只有1M差一点，希望能作参考吧
[master.txt](https://github.com/PaleNeutron/Pcrd-Wiki/files/2467708/master.txt)
源文件名是0afe803e2dce837ee9ab118d93bbf1d1e1187d5c

**Comment by PaleNeutron** [comment]
OJBK了, 顺便把网站也更新了一下
